---
#cloud_controller_uri: api.vcap.me
service:
  name: atmos
  version: "1.4"
  description: 'Atmos object store'
  plans: ['free']
  tags: ['atmos', 'atmos-1.4', 'object store']
ip_route: localhost
#proxy:
#   host: proxy
#   port: 8080
#   keepalive: true
index: 0
token: "0xdeadbeef"
mbus: nats://localhost:4222
logging:
  level: debug
pid: /var/vcap/sys/run/atmos_service.pid

# atmos configuration
# Not configured by default as it would require revealing
# credentials to a non-local resource.
atmos:
  host: "127.0.0.1"
  port: "443"
  tenant: "tenant"
  tenantadmin: "admin"
  tenantpasswd: "password"
