---

classname: "VCAP::Services::Marketplace::Appdirect::AppdirectMarketplace"

node_timeout: 15

# appdirect configuration
appdirect:
  endpoint: "https://example.com"
  key:    "k"
  secret: "s"

offering_whitelist: [ "mongolab" ]

offering_mapping:
  mongolab:
    name: mongodb
    provider: mongolab
