---
cloud_controller_uri: api.vcap.me
ip_route: localhost
index: 0
mbus: nats://localhost:4222/
logging:
  level: debug

pid: /var/vcap/sys/run/marketplace.pid

# node_timeout is required by base async gateway class. This is defined in #{marketplace}.yml
# since this value is specific to interactions with #{marketplace}

marketplace: test

acls:
  wildcards:
  - "*@example.com"
  users: []

external_uri: "http://test-mpgw.vcap.me"
notification_email_domain: 'space-tabasco.cf-app.com'
refresh_interval: 120

cc_api_version: v1
token: testservicetoken
service_auth_tokens:
  testservice_TestProvider: testservicetoken
  fooservice_FooProvider: fooservicetoken
