---
local_db: sqlite3:/var/vcap/services/redis/redis_node.db
mbus: nats://localhost:4222
base_dir: /var/vcap/services/redis/instances
nfs_dir: /mnt/nfs
ip_route: 127.0.0.1
log_level: DEBUG
pid: /var/vcap/sys/run/redis_node.pid
available_memory: 4096
max_memory: 16
max_swap: 32
node_id: redis_node_1
redis_server_path: redis-server
port_range:
  first: 5000
  last: 25000
