---
service_name: redis
base_dir: /var/vcap/services/redis/instances
snapshots_base_dir: /var/vcap/services/
serialization_base_dir: /var/vcap/services/
local_db: sqlite3:/var/vcap/services/redis/redis_node.db
# Temp directory to save uploaded file
snapshot_quota: 5
tmp_dir: /tmp
resque:
  host: localhost
  port: 5454
index: 0
node_id: redis_node_free_1
download_url_template: http://dl.vcap.me/serialized/#{service}/#{name}?token=#{token}
logging:
  level: debug
# addtional options
command_rename_prefix: protect-command-prefix
gzip_bin: gzip
redis_server_path: redis-server
