---
# cloud_controller_uri: api.vcap.me
service:
  name: redis
  version: "2.2"
  description: 'Redis key-value store service'
  plans: ['free']
  tags: ['redis', 'redis-2.2', 'key-value', 'nosql']
host: localhost
token: "0xdeadbeef"
log_level: DEBUG
redis_mbus: nats://localhost:4222
service_mbus: nats://localhost:4222
pid: /var/vcap/sys/run/redis_service.pid
# allow_over_provisioning: false
