---
#cloud_controller_uri: api.vcap.me
service:
  name: mysql
  version: "5.1"
  description: 'MySQL database service'
  plans: ['free']
  tags: ['mysql', 'mysql-5.1', 'relational']
ip_route: localhost
#proxy:
#   host: proxy
#   port: 8080
#   keepalive: true
index: 0
token: "0xdeadbeef"
logging:
  level: debug
mbus: nats://localhost:4222
pid: /var/vcap/sys/run/mysql_service.pid
node_timeout: 2
# allow_over_provisioning: false
# z_interval: 30
# check_orphan_interval: 3600
# double_check_orphan_interval: 300
