---
capacity: 200
plan: free
local_db: sqlite3:/var/vcap/services/postgresql/postgresql_node.db
base_dir: /var/vcap/services/postgresql/
ip_route: 127.0.0.1
restore_bin: pg_restore
dump_bin: pg_dump
mbus: nats://localhost:4222
index: 0
logging:
  level: debug
pid: /var/vcap/sys/run/postgresql_node.pid
node_id: postgresql_node_free_1
max_db_size: 20
max_long_query: 3
max_long_tx: 30
max_db_conns: 20
db_size_overhead: 5.4
postgresql:
  host: 127.0.0.1
  port: 5432
  user: vcap
  pass: vcap
  database: postgres

# z_interval: 30
# fqdn_hosts: false
