---
capacity: 200
plan: free
local_db: sqlite3:/var/vcap/services/rabbit/rabbit_node.db
base_dir: /var/vcap/services/rabbit/instances
mbus: nats://localhost:4222
index: 0
logging:
  level: debug
ip_route: 127.0.0.1
# max_memory: 16
node_id: rabbit_node_free_1
pid: /var/vcap/sys/run/rabbit_node.pid
migration_nfs: /mnt/appcloud
max_clients: 1000
port_range:
  first: 10001
  last: 20000
admin_port_range:
  first: 20001
  last: 30000
service_log_dir: /var/vcap/sys/service-log/rabbit
service_bin_dir:
  '2.4': /var/vcap/packages/rabbitmq-2.4
  '2.8': /var/vcap/packages/rabbitmq-2.8
  '3.0': /var/vcap/packages/rabbitmq-3.0
  erlang: /var/vcap/packages/erlang
service_common_dir: /var/vcap/store/rabbitmq_common
service_start_timeout: 30
supported_versions: ['2.4', '2.8', '3.0']
default_version: '3.0'
rabbit:
  '2.4':
    config_template: ../../../resources/rabbitmq24.config.erb
  '2.8':
    config_template: ../../../resources/rabbitmq28.config.erb
    disk_free_limit: 13421772
  '3.0':
    config_template: ../../../resources/rabbitmq30.config.erb
    disk_free_limit: 13421772
# z_interval: 30
# max_nats_payload: 1048576
# fqdn_hosts: false
max_disk: 10
image_dir: /var/vcap/services/rabbit/rabbitmq_image
vm_memory_high_watermark: 0.00474
bandwidth_per_second: 0.09
