---
# cloud_controller_uri: api.vcap.me
service:
  name: blob
  version: "1.0"
  description: 'Blob Service'
  plans: ['free']
  tags: ['blob', 'blob-1.0', 'nosql']
ip_route: localhost
#proxy:
#   host: proxy
#   port: 8080
#   keepalive: true
index: 0
token: "0xdeadbeef"
mbus: nats://localhost:4222
logging:
  level: debug
pid: /var/vcap/sys/run/blob_service.pid
# allow_over_provisioning: false
# z_interval: 30
# check_orphan_interval: 3600
# double_check_orphan_interval: 300
