---
#cloud_controller: api.vcap.me
service:
  name: rabbitmq
  version: "2.4"
  description: 'RabbitMQ message queue'
  plans: ['free']
  tags: ['rabbitmq', 'rabitmq-2.4', 'message-queue', 'amqp']
host: localhost
token: "0xdeadbeef"
log_level: DEBUG
mbus: nats://localhost:4222
pid: /var/vcap/sys/run/rabbit_gateway.pid
# allow_over_provision: false
