---
# cloud_controller_uri: api.vcap.me
service:
  name: rabbitmq
  version: "2.4"
  description: 'RabbitMQ message queue'
  plans: ['free']
  tags: ['rabbitmq', 'rabitmq-2.4', 'message-queue', 'amqp']
ip_route: localhost
index: 0
token: "0xdeadbeef"
logging:
  level: debug
mbus: nats://localhost:4222
pid: /var/vcap/sys/run/rabbit_gateway.pid
# allow_over_provision: false
# z_interval: 30
