---
local_db: sqlite3:/var/vcap/services/mongodb/mongodb_node.db
mbus: nats://localhost:4222
index: 0
base_dir: /var/vcap/services/mongodb/instances
ip_route: 127.0.0.1
logging:
  level: debug
pid: /var/vcap/sys/run/mongodb_node.pid
available_memory: 4096
max_memory: 128
node_id: mongodb_node_1
mongod_path: mongod
mongorestore_path: mongorestore
port_range:
  first: 25001
  last: 45000
migration_nfs: /mnt/migration
