---
# cloud_controller_uri: api.vcap.me
service:
  name: mongodb
  version: "1.8"
  description: 'MongoDB NoSQL store'
  plans: ['free']
  tags: ['mongodb', 'mongodb-1.8', 'nosql']
ip_route: localhost
#proxy:
#   host: proxy
#   port: 8080
#   keepalive: true
index: 0
token: "0xdeadbeef"
mbus: nats://localhost:4222
logging:
  level: debug
pid: /var/vcap/sys/run/mongodb_service.pid
# allow_over_provisioning: false
# z_interval: 30
# check_orphan_interval: 3600
# double_check_orphan_interval: 300
