---
# cloud_controller_uri: api.vcap.me
service:
  name: mongodb
  version: "1.8"
  description: 'MongoDB NoSQL store'
  plans: ['free']
  default_plan: free
  tags: ['mongodb', 'mongodb-1.8', 'nosql', 'document']
  supported_versions: ["1.8"]
  version_aliases:
    "current": "1.8"

ip_route: localhost
#proxy:
#   host: proxy
#   port: 8080
#   keepalive: true
index: 0
token: "0xdeadbeef"
mbus: nats://localhost:4222
logging:
  level: debug
pid: /var/vcap/sys/run/mongodb_service.pid
# z_interval: 30
# check_orphan_interval: 3600
# double_check_orphan_interval: 300
resque:
  host: localhost
  port: 5454
download_url_template: http://dl.vcap.me/serialized/%{service}/%{name}/snapshots/%{snapshot_id}?token=%{token}

plan_management:
  plans:
    free:
      low_water: 10
      high_water: 180
      lifecycle:
        snapshots:
          quota: 5
        serialization: enable
        job: enable
      #allow_over_provisioning: false
