---
capacity: 200
plan: free
local_db: sqlite3:/var/vcap/services/mysql/mysql_node.db
base_dir: /var/vcap/services/mysql/data
gzip_bin: gzip
# ip_route: 127.0.0.1
mbus: nats://localhost:4222
index: 0
logging:
  level: debug
pid: /var/vcap/sys/run/mysql_node.pid
node_id: mysql_node_free_1
supported_versions: ['5.5']
default_version: '5.5'
max_db_size: 20
max_long_query: 3
max_long_tx: 30
kill_long_tx: true
max_user_conns: 20
migration_nfs: /mnt/migration
mysql:
  '5.5':
    host: localhost
    port: 3306
    user: root
    pass:
    mysqldump_bin: /var/vcap/packages/mysql55/bin/mysqldump
    mysql_bin: /var/vcap/packages/mysql55/bin/mysql
connection_pool_size:
  min: 5
  max: 10
# connection timeout for all management mysql connection
connection_wait_timeout: 10
max_disk: 128
use_warden: true
warden:
  port_range:
    first: 25001
    last:  45000
  service_log_dir: /var/vcap/services/mysql/log
  service_bin_dir:
    '5.5': /var/vcap/packages/mysql55
  service_common_dir: /var/vcap/store/mysql_common
  image_dir: /var/vcap/services/mysql/image
  service_start_timeout: 3
  filesystem_quota: false

# z_interval: 30
# max_nats_payload: 1048576
# fqdn_hosts: false
# op_time_limit: 6
